# Generated by Django 3.0.4 on 2020-03-24 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 24, 10, 26, 9, 728434, tzinfo=utc))),
            ],
        ),
    ]
